Repository pgRouting/GSoC-pgRouting, pull requests merged in 2020-07, with the labels that each got.

#63 pgr_makeConnected GSoC 2020 Week 7
  doc/planarGraph/pgr_topologicalSort.rst
  docqueries/planarGraph/doc-pgr_boyerMyrvold.result
  docqueries/planarGraph/doc-pgr_boyerMyrvold.test.sql
  include/makeConnected/pgr_makeConnected.hpp
  include/planarGraph/pgr_boyerMyrvold.hpp
  pgtap/makeConnected/makeConnected-edge-cases.sql
  src/kargersContraction/kargersContraction.c
  test.sh
Labels: Himanshu

#72 Closes #70 adds code that sorts the edges
  include/cpp_common/pgr_base_graph.hpp
Labels: Ashish Kumar, ordering

#73 Closes #69 adds allpairs pgtap tests to check output after rows ordering
  pgtap/allpairs/floydWarshall-rows-check.sql
  pgtap/allpairs/johnson-rows-check.sql
Labels: Ashish Kumar, ordering

#76 Closes #75 adds chinese postman pgtap tests to check output after row ordering
  pgtap/chinese/chinesePostman/chinesePostman-rows-check.sql
  pgtap/chinese/chinesePostmanCost/chinesePostmanCost-rows-check.sql
Labels: Ashish Kumar, ordering

#81 Fixing astar ordering issue
  pgtap/astar/aStarCost-rows-check.sql
  pgtap/astar/astar-rows-check.sql
  src/astar/astar_driver.cpp
Labels: Ashish Kumar, enhancement, official, ordering

#88 Fixing dagShortestPath ordering issue
  pgtap/dagShortestPath/dagShortestPath-rows-check.sql
  src/dagShortestPath/dagShortestPath_driver.cpp
Labels: Ashish Kumar, enhancement, experimental, ordering

#86 Fixing contraction ordering issue
  pgtap/contraction/contraction-rows-check.sql
  src/contraction/contractGraph_driver.cpp
Labels: Ashish Kumar, enhancement, official, ordering

#82 Fixing bdAstar ordering issue
  pgtap/bdAstar/bdAstar-rows-check.sql
  pgtap/bdAstar/bdAstarCost-rows-check.sql
Labels: Ashish Kumar, enhancement, official, ordering

#83 Fixing bdDijkstra ordering issue
  pgtap/bdDijkstra/bdDijkstra-rows-check.sql
  pgtap/bdDijkstra/bdDijkstraCost-rows-check.sql
  src/bdDijkstra/bdDijkstra_driver.cpp
Labels: Ashish Kumar, enhancement, official, ordering

#87 Fixing costMatrix ordering issue
  pgtap/costMatrix/aStarCostMatrix/aStarCostMatrix-rows-check.sql
  pgtap/costMatrix/bdAstarCostMatrix/bdAstarCostMatrix-rows-check.sql
  pgtap/costMatrix/bdDijkstraCostMatrix/bdDijkstraCostMatrix-rows-check.sql
  pgtap/costMatrix/dijkstraCostMatrix/dijkstraCostMatrix-rows-check.sql
  pgtap/costMatrix/withPointsCostMatrix/withPointsCostMatrix-rows-check.sql
Labels: Ashish Kumar, enhancement, official, ordering, proposed

#90 Fixing driving_distance ordering issue
  pgtap/driving_distance/dijkstraDD-rows-check.sql
  pgtap/driving_distance/withPointsDD-rows-check.sql
  src/driving_distance/drivedist_driver.cpp
Labels: Ashish Kumar, enhancement, official, ordering, proposed

#94 Fixing mincut ordering issue
  pgtap/mincut/stoerWagner-rows-check.sql
Labels: Ashish Kumar, enhancement, experimental, ordering

#96 Fixing spanningTree ordering issue
  pgtap/spanningTree/kruskal/kruskal/kruskal-rows-check.sql
  pgtap/spanningTree/kruskal/kruskalBFS/kruskalBFS-rows-check.sql
  pgtap/spanningTree/kruskal/kruskalDD/kruskalDD-rows-check.sql
  pgtap/spanningTree/kruskal/kruskalDFS/kruskalDFS-rows-check.sql
  pgtap/spanningTree/prim/prim/prim-rows-check.sql
  pgtap/spanningTree/prim/primBFS/primBFS-rows-check.sql
  pgtap/spanningTree/prim/primDD/primDD-rows-check.sql
  pgtap/spanningTree/prim/primDFS/primDFS-rows-check.sql
  src/spanningTree/kruskal_driver.cpp
  src/spanningTree/prim_driver.cpp
Labels: Ashish Kumar, enhancement, official, ordering

#98 Fixing topology ordering issue
  pgtap/topology/extractVertices/extractVertices-rows-check.sql
Labels: Ashish Kumar, enhancement, experimental, ordering

#97 Fixing topologicalSort ordering issue
  pgtap/topologicalSort/topologicalSort-rows-check.sql
  src/topologicalSort/topologicalSort_driver.cpp
Labels: Ashish Kumar, enhancement, experimental, ordering

#101 Fixing withPoints ordering issue
  pgtap/withPoints/withPoints-rows-check.sql
  pgtap/withPoints/withPointsCost-rows-check.sql
Labels: Ashish Kumar, enhancement, ordering, proposed

#99 Fixing transitiveClosure ordering issue
  pgtap/transitiveClosure/transitiveClosure-rows-check.sql
  src/transitiveClosure/transitiveClosure_driver.cpp
Labels: Ashish Kumar, enhancement, experimental, ordering

#89 Fixing dijkstra ordering issue
  docqueries/lineGraph/doc-pgr_lineGraphFull.result
  pgtap/dijkstra/dijkstra-rows-check.sql
  pgtap/dijkstra/dijkstraCost-rows-check.sql
  pgtap/dijkstra/dijkstraVia-rows-check.sql
  src/dijkstra/dijkstra_driver.cpp
Labels: Ashish Kumar, enhancement, official, ordering, proposed

#92 Fixing lineGraph ordering issue
  pgtap/lineGraph/lineGraph/lineGraph-rows-check.sql
  pgtap/lineGraph/lineGraphFull/lineGraphFull-rows-check.sql
Labels: Ashish Kumar, enhancement, experimental, ordering

#91 Fixing ksp ordering issue
  pgtap/ksp/ksp-rows-check.sql
  pgtap/ksp/withPointsKSP-rows-check.sql
Labels: Ashish Kumar, enhancement, official, ordering, proposed

#93 Fixing max_flow ordering issue
  pgtap/max_flow/boykovKolmogorov-rows-check.sql
  pgtap/max_flow/edgedisjointpaths-rows-check.sql
  pgtap/max_flow/edmondsKarp-rows-check.sql
  pgtap/max_flow/maxCardinalityMatch-rows-check.sql
  pgtap/max_flow/maxFlow/maxFlow-rows-check.sql
  pgtap/max_flow/maxFlowMinCost/maxFlowMinCost-rows-check.sql
  pgtap/max_flow/maxFlowMinCost/maxFlowMinCost_Cost-rows-check.sql
  pgtap/max_flow/pushRelabel-rows-check.sql
Labels: Ashish Kumar, enhancement, experimental, official, ordering

#100 Fixing tsp ordering issue
  pgtap/tsp/tsp-rows-check.sql
Labels: Ashish Kumar, enhancement, official, ordering

#80 GSoC-2020- pgr_bipartite()[Week 8]
  Bipaertite_run.sh
  configuration.conf
  doc/bipartite/CMakeLists.txt
  doc/bipartite/pgr_bipartite.rst
  docqueries/bipartite/CMakeLists.txt
  docqueries/bipartite/doc-bipartite.result
  docqueries/bipartite/doc-bipartite.test.sql
  docqueries/bipartite/test.conf
  include/LTDTree/pgr_LTDTree_driver.hpp
  include/bipartite/pgr_bipartite_driver.hpp
  include/c_types/pgr_bipartite_rt.h
  include/drivers/bipartite/bipartite_driver.h
  include/spanningTree/pgr_mrt_driver.hpp
  pgtap/LTDTree/ltdtree-edge-cases.sql
  pgtap/bipartite/bipartite-edge-cases.sql
  pgtap/bipartite/bipartite-innerQuery.sql
  pgtap/bipartite/no_crash_test-bipartite.sql
  pgtap/bipartite/pgr_bipartite_types_check.sql
  runWithDoc.sh
  runspan.sh
  sql/bipartite/CMakeLists.txt
  sql/bipartite/_bipartite.sql
  sql/bipartite/bipartite.sql
  sql/sigs/pgrouting--3.2.0.sig
  src/bipartite/CMakeLists.txt
  src/bipartite/bipartite.c
  src/bipartite/bipartite_driver.cpp
Labels: Prakash
