Repository pgRouting/GSoC-pgRouting, pull requests merged in 2022-08, with the labels that each got.

#248 GSoC 2022: Nitish Chauhan Week 8
  doc/circuits/hawickCircuits.rst
  doc/conf.py.in
  docqueries/circuits/hawickCircuits.result
  include/circuits/hawickcircuits.hpp
  include/drivers/circuits/hawickcircuits_driver.h
  pgtap/circuits/hawickCircuits/edge_cases.pg
  pgtap/circuits/hawickCircuits/types_check.pg
  sql/circuits/_hawickCircuits.sql
  sql/circuits/hawickCircuits.sql
  sql/sigs/pgrouting--3.4.sig
  src/circuits/hawickCircuits.c
  src/circuits/hawickCircuits_driver.cpp
Labels: nitish-2022

#249 GSoC 2022 : Shobhit Chaurasia Week 8
  include/ordering/cuthillMckeeOrdering.hpp
  pgtap/ordering/cuthillMckeeOrdering/no_crash_test.pg
Labels: shobhit-2022

#251 GSoC 2022: Nitish Chauhan Week 9
  docqueries/circuits/hawickCircuits.result
  include/circuits/hawickcircuits.hpp
  pgtap/circuits/hawickCircuits/inner_query.pg
  pgtap/circuits/hawickCircuits/no_crash_test.pg
Labels: nitish-2022

#250 GSoC 2022 : Shobhit Chaurasia Week 9
  include/ordering/cuthillMckeeOrdering.hpp
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: shobhit-2022

#253 GSoC 2022: Nitish Chauhan Week 10
  docqueries/circuits/hawickCircuits.result
  include/circuits/hawickcircuits.hpp
  pgtap/circuits/hawickCircuits/edge_cases.pg
Labels: nitish-2022

#257 GSoC 2022: Manas Sivakumar Week 11
  configuration.conf
  doc/general/CMakeLists.txt
  doc/general/experimental.rst
  doc/general/or_tools-category.rst
  doc/or_tools/bin_packing.rst
  doc/or_tools/knapsack.rst
  doc/or_tools/multiple_knapsack.rst
  docqueries/or_tools/CMakeLists.txt
  docqueries/or_tools/bin_packing.result
  docqueries/or_tools/bin_packing.test.sql
  docqueries/or_tools/doc-vrp_bin_packing.result
  docqueries/or_tools/doc-vrp_bin_packing.test.sql
  docqueries/or_tools/doc-vrp_knapsack.result
  docqueries/or_tools/doc-vrp_knapsack.test.sql
  docqueries/or_tools/doc-vrp_multiple_knapsack.result
  docqueries/or_tools/doc-vrp_multiple_knapsack.test.sql
  docqueries/or_tools/knapsack.result
  docqueries/or_tools/multiple_knapsack.result
  docqueries/or_tools/multiple_knapsack.test.sql
  docqueries/or_tools/test.conf
  pgtap/or_tools/inner_query.sql
  pgtap/or_tools/types_check.sql
  sql/or_tools/bin_packing.sql
  sql/or_tools/knapsack.sql
  sql/or_tools/multiple_knapsack.sql
  sql/or_tools/plpython/composite_types.sql
  sql/or_tools/plpython/envir.sql
  sql/or_tools/plpython/mulitple_rows.sql
  sql/sigs/vrprouting--0.4.sig
  tools/testers/ortoolsdata.sql
Labels: manas-2022

#256 GSoC 2022: Nitish Chauhan Week 11
  pgtap/circuits/hawickCircuits/edge_cases.pg
Labels: nitish-2022

#255 GSoC 2022 : Shobhit Chaurasia Week 11
  doc/ordering/cuthillMckeeOrdering.rst
  doc/ordering/ordering-family.rst
  docqueries/ordering/cuthillMckeeOrdering.result
  docqueries/ordering/cuthillMckeeOrdering.test.sql
  include/drivers/ordering/cuthillMckeeOrdering_driver.h
  include/ordering/cuthillMckeeOrdering.hpp
  pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg
  pgtap/ordering/cuthillMckeeOrdering/types_check.pg
  sql/ordering/_cuthillMckeeOrdering.sql
  sql/ordering/cuthillMckeeOrdering.sql
  sql/sigs/pgrouting--3.4.sig
  src/ordering/cuthillMckeeOrdering.c
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: shobhit-2022

#258 GSoC 2022 : Shobhit Chaurasia Week 12
  doc/ordering/cuthillMckeeOrdering.rst
  include/c_types/ordering_rt.h
  include/ordering/cuthillMckeeOrdering.hpp
  pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg
  src/ordering/cuthillMckeeOrdering.c
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: shobhit-2022
