Repository pgRouting/GSoC-pgRouting, pull requests merged in 2022-07, with the labels that each got.

#223 GSoC 2022: Nitish Chauhan Week 3
  configuration.conf
  doc/circuits/CMakeLists.txt
  include/c_types/circuits_rt.h
  include/circuits/hawickcircuits.hpp
  include/drivers/circuits/hawickcircuits_driver.h
  sql/circuits/CMakeLists.txt
  src/circuits/CMakeLists.txt
Labels: nitish-2022

#225 GSoC 2022 Manas Sivakumar : Third and Fourth Week
  .github/workflows/ubuntu.yml
  .gitignore
  CMakeLists.txt
  configuration.conf
  doc/general/introduction.rst
  doc/or_tools/CMakeLists.txt
  doc/or_tools/knapsack.rst
  docqueries/or_tools/CMakeLists.txt
  docqueries/or_tools/knapsack.rst
  docqueries/or_tools/knapsack.test.sql
  include/drivers/or_tools/knapsack_driver.h
  sql/or_tools/CMakeLists.txt
  sql/or_tools/_knapsack.sql
  sql/or_tools/knapsack.sql
  src/knapsack/knapsack.c
  src/knapsack/knapsack_driver.cpp
  src/or_tools/CMakeLists.txt
  src/or_tools/knapsack.c
  src/or_tools/knapsack_driver.cpp
Labels: manas-2022

#227 GSoC 22 Manas Sivakumar : Week 4
  .github/workflows/boost_version.yml
  .github/workflows/check-queries.yml
  .github/workflows/clang.yml
  .github/workflows/doc-check.yml
  .github/workflows/documentation.yml
  .github/workflows/locale-and-website.yml
  .github/workflows/macos.yml
  .github/workflows/release.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  include/drivers/or_tools/knapsack_driver.h
  src/or_tools/knapsack.c
  src/or_tools/knapsack_driver.cpp
  tools/developer/run.sh
Labels: manas-2022

#228 GSoC 2022: Nitish Chauhan Week 4
  include/circuits/hawickcircuits.hpp
  src/circuits/CMakeLists.txt
  src/circuits/hawickCircuits.c
  src/circuits/hawickCircuits_driver.cpp
Labels: nitish-2022

#226 GSoC 2022 : Shobhit Chaurasia Week 4
  docqueries/ordering/cuthillMckeeOrdering.test.sql
  include/drivers/ordering/cuthillMckeeOrdering_driver.h
  include/ordering/cuthillMckeeOrdering.hpp
  src/ordering/cuthillMckeeOrdering.c
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: shobhit-2022

#231 GSoC 2022: Nitish Chauhan Week 5
  configuration.conf
  doc/circuits/CMakeLists.txt
  doc/circuits/hawickCircuits.rst
  doc/src/experimental.rst
  docqueries/circuits/CMakeLists.txt
  docqueries/circuits/hawickCircuits.result
  docqueries/circuits/hawickCircuits.test.sql
  docqueries/circuits/test.conf
  include/c_types/circuits_rt.h
  include/circuits/hawickcircuits.hpp
  include/drivers/circuits/hawickcircuits_driver.h
  sql/circuits/_hawickCircuits.sql
  sql/circuits/hawickCircuits.sql
  sql/sigs/pgrouting--3.4.sig
  src/circuits/hawickCircuits.c
  src/circuits/hawickCircuits_driver.cpp
Labels: nitish-2022

#232 GSoC 2022: Shobhit Chaurasia Week 5
  configuration.conf
  doc/ordering/CMakeLists.txt
  doc/ordering/cuthillMckeeOrdering.rst
  doc/src/experimental.rst
  docqueries/ordering/cuthillMckeeOrdering.result
  docqueries/ordering/cuthillMckeeOrdering.test.sql
  include/ordering/cuthillMckeeOrdering.hpp
  sql/sigs/pgrouting--3.4.sig
Labels: shobhit-2022

#234 GSoC 2022 : Shobhit Chaurasia Week 6
  doc/conf.py.in
  doc/ordering/CMakeLists.txt
  doc/ordering/cuthillMckeeOrdering.rst
  doc/ordering/ordering-family.rst
  doc/src/experimental.rst
  docqueries/ordering/cuthillMckeeOrdering.result
  docqueries/ordering/cuthillMckeeOrdering.test.sql
  include/drivers/ordering/cuthillMckeeOrdering_driver.h
  include/ordering/cuthillMckeeOrdering.hpp
  pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg
  pgtap/ordering/cuthillMckeeOrdering/inner_query.pg
  pgtap/ordering/cuthillMckeeOrdering/types_check.pg
  sql/ordering/_cuthillMckeeOrdering.sql
  sql/ordering/cuthillMckeeOrdering.sql
  src/ordering/cuthillMckeeOrdering.c
Labels: shobhit-2022

#235 GSoC 2022: Nitish Chauhan Week 6
  doc/circuits/hawickCircuits.rst
  docqueries/circuits/hawickCircuits.result
  include/c_types/circuits_rt.h
  include/circuits/hawickcircuits.hpp
  pgtap/circuits/hawickCircuits/types_check.pg
  sql/circuits/_hawickCircuits.sql
  sql/circuits/hawickCircuits.sql
  src/circuits/hawickCircuits.c
Labels: nitish-2022

#236 GSoC 22 : Manas Sivakumar Week 6
  .gitignore
  .vscode/settings.json
  CMakeLists.txt
  test_ortools/README.md
  test_ortools/employee_scheduler.cc
  test_ortools/knapsack_0_1.cc
  test_ortools/multiple_knapsack_0_1.cc
Labels: manas-2022

#242 GSoC 2022: Nitish Chauhan Week 7
  doc/conf.py.in
  docqueries/circuits/hawickCircuits.result
  include/circuits/Example.cpp
  include/circuits/hawickcircuits.hpp
  src/circuits/hawickCircuits_driver.cpp
Labels: nitish-2022

#244 GSoC 2022 : Shobhit Chaurasia Week 7
  include/ordering/cuthillMckeeOrdering.hpp
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: shobhit-2022

#241 GSoC 22 : Manas Sivakumar Week 7
  CMakeLists.txt
  configuration.conf
  sql/or_tools/CMakeLists.txt
  sql/or_tools/_knapsack.sql
  sql/or_tools/bin_packing.sql
  sql/or_tools/composite_types.sql
  sql/or_tools/example.sql
  sql/or_tools/knapsack.sql
  sql/or_tools/mulitple_rows.sql
  sql/or_tools/multiple_knapsack.sql
  sql/or_tools/or.py
  sql/or_tools/or_tools_example.sql
  sql/or_tools/plpython.md
  sql/or_tools/printing.sql
  sql/pg_controls/vrprouting.control
  src/or_tools/CMakeLists.txt
  tools/testers/doc_queries_generator.pl
  tools/testers/setup_db.sql
Labels: manas-2022
