Repository pgRouting/GSoC-pgRouting, pull requests merged in 2022-06, with the labels that each got.

#216 GSoC 2022: Shobhit Chaurasia Week 1
  doc/src/pgRouting-introduction.rst
Labels: shobhit-2022

#211 GSoC 2022: Nitish Chauhan Week 1
  doc/src/pgRouting-introduction.rst
  sql/circuits/CMakeLists.txt
  sql/circuits/_hawickCircuits.sql
  sql/circuits/hawickCircuits.sql
  src/circuits/CMakeLists.txt
  src/circuits/hawickCircuits.c
  src/circuits/hawickCircuits_driver.cpp
Labels: nitish-2022

#217 GSoC 2022: Sanskar Bhushan Week 1
  doc/src/pgRouting-introduction.rst
  src/metrics/CMakeLists.txt
  src/metrics/edgeBetweennessCentrality.c
  src/metrics/edgeBetweennessCentrality_driver.cpp
  src/metrics/ithBandwidth.c
  src/metrics/ithBandwidth_driver.cpp
  src/metrics/vertexBetweennessCentrality.c
  src/metrics/vertexBetweennessCentrality_driver.cpp
Labels: sanskar-2022

#215 GSoC 2022: Manas Sivakumar Week 1
  doc/general/introduction.rst
Labels: manas-2022

#220 GSoC 2022: Shobhit Chaurasia Week 2
  doc/ordering/CMakeLists.txt
  include/drivers/ordering/cuthillMckeeOrdering_driver.h
  sql/ordering/CMakeLists.txt
  sql/ordering/_cuthillMckeeOrdering.sql
  sql/ordering/cuthillMckeeOrdering.sql
  src/ordering/CMakeLists.txt
  src/ordering/cuthillMckeeOrdering.c
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: shobhit-2022

#219 Manas week 2
  configuration.conf
  doc/or_tools/knapsack.rst
  docqueries/or_tools/knapsack.rst
  sql/or_tools/knapsack/CMakeLists.txt
  sql/or_tools/knapsack/_knapsack.sql
  sql/or_tools/knapsack/knapsack.sql
  src/knapsack/CMakeLists.txt
  src/knapsack/knapsack.c
  src/knapsack/knapsack_driver.cpp
  tools/testers/matrix_new_values.tar.gz
Labels: manas-2022

#221 GSoC 2022: Sanskar Bhushan Week 2
  sql/metrics/CMakeLists.txt
  sql/metrics/_edgeBetweennessCentrality.sql
  sql/metrics/_ithBandwidth.sql
  sql/metrics/_vertexBetweennessCentrality.sql
  sql/metrics/edgeBetweennessCentrality.sql
  sql/metrics/ithBandwidth.sql
  sql/metrics/vertexBetweennessCentrality.sql
Labels: sanskar-2022
