Repository pgRouting/GSoC-pgRouting, pull requests merged in 2023-08, with the labels that each got.

#336 GSoC 2023: Aniket Agarwal week 10
  pgtap/ksp/ksp/inner_query.pg
  pgtap/ksp/ksp/no_crash_test.pg
  pgtap/ksp/ksp/types_check.pg
  sql/scripts/build-extension-update-files.pl
Labels: Aniket-2023

#337 GSoC 2023 : Abhinav Jain Week 10
  pgtap/ksp/withPointsKSP/inner_query.pg
  pgtap/ksp/withPointsKSP/no_crash_test.pg
  pgtap/ksp/withPointsKSP/types_check.pg
  src/ksp/withPoints_ksp.c
Labels: Abhinj-2023

#335 GSoC 2023: YigeHuang week 10
  doc/withPoints/pgr_withPointsDD.rst
  pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg
  pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg
  pgtap/withPoints/withPointsDD/inner_query.pg
  pgtap/withPoints/withPointsDD/no_crash_test.pg
  sql/driving_distance/withPointsDD.sql
  sql/scripts/build-extension-update-files.pl
Labels: yige-2023

#343 GSoC 2023: Aniket Agarwal week 11
  .gitignore
  doc/conf.py.in
  doc/ksp/pgr_KSP.rst
  doc/src/migration.rst
  include/c_types/path_rt.h
  include/cpp_common/basePath_SSEC.hpp
  include/yen/pgr_ksp.hpp
  src/common/basePath_SSEC.cpp
  src/ksp/ksp.c
  src/ksp/ksp_driver.cpp
  src/ksp/withPoints_ksp.c
  src/ksp/withPoints_ksp_driver.cpp
Labels: Aniket-2023

#341 GSoC 2023: Yige Huang week 11
  include/drivers/driving_distance/withPoints_dd_driver.h
  src/driving_distance/many_to_dist_withPointsDD.c
  src/driving_distance/withPoints_dd_driver.cpp
Labels: yige-2023

#340 GSoC 2023: Abhinav Jain Week 11
  doc/conf.py.in
  doc/withPoints/pgr_withPointsKSP.rst
  docqueries/src/migration.result
  docqueries/src/migration.test.sql
  include/cpp_common/basePath_SSEC.hpp
  include/drivers/yen/withPoints_ksp_driver.h
  src/common/basePath_SSEC.cpp
  src/ksp/ksp.c
  src/ksp/ksp_driver.cpp
  src/ksp/withPoints_ksp.c
  src/ksp/withPoints_ksp_driver.cpp
Labels: Abhinj-2023

#338 GSoC 2023: Aryan Gupta week 11
  include/dijkstra/drivingDist.hpp
  include/dijkstra/v4drivingDist.hpp
  include/drivers/driving_distance/drivedist_driver.h
  include/drivers/driving_distance/v4drivedist_driver.h
  pgtap/dijkstra/driving_distance/edge_cases/issue_1152.pg
  pgtap/dijkstra/driving_distance/edge_cases/issue_519.pg
  pgtap/dijkstra/driving_distance/inner_query.pg
  pgtap/dijkstra/driving_distance/no_crash_test.pg
  pgtap/dijkstra/driving_distance/types_check.pg
  src/driving_distance/CMakeLists.txt
  src/driving_distance/drivedist_driver.cpp
  src/driving_distance/driving_distance.c
  src/driving_distance/v4drivedist_driver.cpp
  src/driving_distance/withPoints_dd_driver.cpp
Labels: aryan-2023

#346 Modifying withpointsdd
  doc/driving_distance/pgr_drivingDistance.rst
  doc/src/migration.rst
  doc/src/pgRouting-introduction.rst
  doc/withPoints/pgr_withPointsDD.rst
  docqueries/src/migration.result
  docqueries/src/migration.test.sql
  docqueries/withPoints/doc-pgr_withPointsDD.result
  docqueries/withPoints/doc-pgr_withPointsDD.test.sql
  include/drivers/driving_distance/withPoints_dd_driver.h
  include/driving_distance/withPointsDD.hpp
  pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg
  pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg
  pgtap/withPoints/withPointsDD/inner_query.pg
  pgtap/withPoints/withPointsDD/no_crash_test.pg
  pgtap/withPoints/withPointsDD/types_check.pg
  sql/driving_distance/_withPointsDD.sql
  sql/driving_distance/withPointsDD.sql
  sql/sigs/pgrouting--3.6.sig
  src/driving_distance/many_to_dist_withPointsDD.c
  src/driving_distance/withPoints_dd_driver.cpp
  src/withPoints/get_new_queries.cpp
Labels: yige-2023

#345 GSoC 2023: Aniket Agarwal week 12
  doc/ksp/pgr_KSP.rst
Labels: Aniket-2023

#350 GSoC 2023: Yige Huang week 12
  doc/src/migration.rst
  doc/withPoints/pgr_withPointsDD.rst
  pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg
  pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg
  sql/scripts/build-extension-update-files.pl
Labels: yige-2023
