Repository pgRouting/GSoC-pgRouting, pull requests merged in 2023-06, with the labels that each got.

#293 GSoC 2023: Aryan Gupta Week 1
  doc/src/pgRouting-introduction.rst
Labels: aryan-2023

#291 GSoC 2023: Yige Huang Week 1
  doc/src/pgRouting-introduction.rst
Labels: yige-2023

#295 GSoC 2023: Aniket Agarwal Week 2
  .gitignore
  doc/src/pgRouting-introduction.rst
  include/c_types/path_rt.h
  include/drivers/yen/ksp_driver.h
  include/yen/pgr_ksp.hpp
  sql/ksp/_ksp.sql
  sql/ksp/ksp.sql
  src/common/basePath_SSEC.cpp
  src/ksp/ksp.c
  src/ksp/ksp_driver.cpp
Labels: Aniket-2023

#299 GSoC 2023: Yige Huang week 2
  docqueries/withPoints/doc-pgr_withPointsDD.result
  docqueries/withPoints/doc-pgr_withPointsDD.test.sql
  pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg
  pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg
  pgtap/withPoints/withPointsDD/types_check.pg
  sql/driving_distance/_withPointsDD.sql
  sql/driving_distance/withPointsDD.sql
  src/driving_distance/many_to_dist_withPointsDD.c
Labels: yige-2023

#296 GSoC 2023: Aryan Gupta Week 2
  .gitignore
  docqueries/driving_distance/dijksraDD-issue729.result
  docqueries/driving_distance/dijksraDD-issue729.test.sql
  docqueries/driving_distance/doc-pgr_drivingDistance.result
  pgtap/dijkstra/driving_distance/edge_cases/issue_1152.pg
  pgtap/dijkstra/driving_distance/edge_cases/issue_519.pg
  pgtap/dijkstra/driving_distance/types_check.pg
  sql/driving_distance/_drivingDistance.sql
  sql/driving_distance/drivingDistance.sql
Labels: aryan-2023

#297 GSoC 2023 - Abhinav Jain Week 2
  include/drivers/yen/withPoints_ksp_driver.h
  include/yen/pgr_ksp.hpp
  src/ksp/withPoints_ksp.c
  src/ksp/withPoints_ksp_driver.cpp
Labels: Abhinj-2023

#306 GSoC 2023: Abhinav Jain week 3
  include/drivers/yen/withPoints_ksp_driver.h
  sql/ksp/_withPointsKSP.sql
  sql/ksp/withPointsKSP.sql
  src/ksp/withPoints_ksp.c
Labels: Abhinj-2023

#307 GSoC 2023: Aniket Agarwal Week 4
  include/cpp_common/basePath_SSEC.hpp
  include/drivers/yen/v4ksp_driver.h
  pgtap/ksp/ksp/types_check.pg
  sql/ksp/_ksp.sql
  sql/ksp/ksp.sql
  sql/sigs/pgrouting--3.6.sig
  src/common/basePath_SSEC.cpp
  src/ksp/CMakeLists.txt
  src/ksp/v4ksp.c
  src/ksp/v4ksp_driver.cpp
Labels: Aniket-2023

#309 GSoC 2023: Yige Huang Week 4
  include/drivers/driving_distance/v6withPoints_dd_driver.h
  include/drivers/driving_distance/withPoints_dd_driver.h
  include/driving_distance/withPointsDD.hpp
  sql/driving_distance/_withPointsDD.sql
  sql/driving_distance/withPointsDD.sql
  src/driving_distance/CMakeLists.txt
  src/driving_distance/many_to_dist_withPointsDD.c
  src/driving_distance/v4withPointsDD.c
  src/driving_distance/v4withPoints_dd_driver.cpp
  src/driving_distance/withPoints_dd_driver.cpp
Labels: yige-2023

#310 GSoC 2023: Aryan Gupta week 4
  .gitignore
  include/c_types/path_rtdd.h
  include/dijkstra/v4drivingDist.hpp
  include/drivers/driving_distance/v4drivedist_driver.h
  sql/driving_distance/_drivingDistance.sql
  sql/driving_distance/drivingDistance.sql
  src/driving_distance/v4drivedist_driver.cpp
  src/driving_distance/v4driving_distance.c
Labels: aryan-2023
