Repository pgRouting/GSoC-pgRouting, pull requests merged in 2023-07, with the labels that each got.

#313 GSoC 2023: Yige Huang Week 5
  include/drivers/driving_distance/withPoints_dd_driver.h
  include/driving_distance/withPointsDD.hpp
  sql/driving_distance/_withPointsDD.sql
  sql/driving_distance/withPointsDD.sql
  src/driving_distance/v4withPointsDD.c
  src/driving_distance/v4withPoints_dd_driver.cpp
Labels: yige-2023

#312 GSoC 2023: Aniket Agarwal Week 5
  docqueries/ksp/doc-ksp.result
  pgtap/ksp/ksp/edge_cases/issue_1891.pg
  pgtap/ksp/ksp/types_check.pg
  sql/ksp/ksp.sql
Labels: Aniket-2023

#311 GSoC 2023: Aryan Gupta week 5
  docqueries/driving_distance/pgr_drivingDistance.result
  docqueries/driving_distance/pgr_drivingDistance.test.sql
  include/c_types/path_dd_rt.h
  include/dijkstra/v4drivingDist.hpp
  include/drivers/driving_distance/v4drivedist_driver.h
  sql/sigs/pgrouting--3.6.sig
  src/driving_distance/CMakeLists.txt
  src/driving_distance/v4drivedist_driver.cpp
  src/driving_distance/v4driving_distance.c
Labels: aryan-2023

#316 GSoC 2023: Aniket Agarwal Week 6
  doc/ksp/pgr_KSP.rst
  docqueries/ksp/doc-ksp.result
  docqueries/ksp/doc-ksp.test.sql
Labels: Aniket-2023

#318 GSoC 2023: Yige Huang Week 6
  docqueries/withPoints/doc-pgr_withPointsDD.result
  include/drivers/driving_distance/withPoints_dd_driver.h
  sql/driving_distance/withPointsDD.sql
  sql/sigs/pgrouting--3.6.sig
  src/driving_distance/v4withPointsDD.c
  src/driving_distance/v4withPoints_dd_driver.cpp
Labels: yige-2023

#315 GSoC 2023: Aryan Gupta week 6
  include/c_types/path_dd_rt.h
  include/dijkstra/v4drivingDist.hpp
  include/drivers/driving_distance/v4drivedist_driver.h
  sql/driving_distance/_drivingDistance.sql
  sql/driving_distance/drivingDistance.sql
  src/driving_distance/v4drivedist_driver.cpp
  src/driving_distance/v4driving_distance.c
Labels: aryan-2023

#324 GSoC 2023: Yige Huang week 7
  doc/driving_distance/pgr_drivingDistance.rst
  doc/withPoints/pgr_withPointsDD.rst
  docqueries/withPoints/doc-pgr_withPointsDD.result
  docqueries/withPoints/doc-pgr_withPointsDD.test.sql
  include/drivers/driving_distance/withPoints_dd_driver.h
  include/driving_distance/withPointsDD.hpp
  pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg
  pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg
  pgtap/withPoints/withPointsDD/inner_query.pg
  pgtap/withPoints/withPointsDD/no_crash_test.pg
  pgtap/withPoints/withPointsDD/types_check.pg
  sql/driving_distance/_withPointsDD.sql
  sql/driving_distance/withPointsDD.sql
  src/driving_distance/CMakeLists.txt
  src/driving_distance/withPointsDD.c
  src/driving_distance/withPointsDD_driver.cpp
  src/withPoints/get_new_queries.cpp
Labels: yige-2023

#321 GSoC 2023: Aryan Gupta week 7
  .gitignore
  doc/driving_distance/pgr_drivingDistance.rst
  doc/src/pgRouting-introduction.rst
  docqueries/driving_distance/CMakeLists.txt
  docqueries/driving_distance/dijksraDD-issue729.result
  docqueries/driving_distance/dijksraDD-issue729.test.sql
  docqueries/driving_distance/doc-pgr_drivingDistance.result
  docqueries/driving_distance/doc-pgr_drivingDistance.test.sql
  docqueries/driving_distance/pgr_drivingDistance.result
  docqueries/driving_distance/pgr_drivingDistance.test.sql
  docqueries/driving_distance/test.conf
  pgtap/dijkstra/driving_distance/edge_cases/issue_1152.pg
  pgtap/dijkstra/driving_distance/edge_cases/issue_519.pg
  pgtap/dijkstra/driving_distance/types_check.pg
  sql/driving_distance/_drivingDistance.sql
  sql/driving_distance/drivingDistance.sql
  sql/sigs/pgrouting--3.6.sig
  src/driving_distance/CMakeLists.txt
  src/driving_distance/driving_distance.c
  src/driving_distance/many_to_dist_driving_distance.c
Labels: aryan-2023

#319 GSoC 2023: Abhinav Jain Week 7
  docqueries/withPoints/CMakeLists.txt
  docqueries/withPoints/doc-pgr_withPointsKSP.result
  docqueries/withPoints/test.conf
  docqueries/withPoints/withPointsKSP.result
  docqueries/withPoints/withPointsKSP.test.sql
  include/drivers/yen/withPoints_ksp_driver.h
  sql/ksp/_withPointsKSP.sql
  sql/ksp/withPointsKSP.sql
  src/ksp/withPoints_ksp.c
  src/ksp/withPoints_ksp_driver.cpp
Labels: Abhinj-2023

#322 GSoC 2023: Aniket Agarwal week 7
  doc/ksp/pgr_KSP.rst
  include/drivers/yen/ksp_driver.h
  include/drivers/yen/v4ksp_driver.h
  pgtap/ksp/ksp/types_check.pg
  src/ksp/CMakeLists.txt
  src/ksp/ksp.c
  src/ksp/ksp_driver.cpp
  src/ksp/v4ksp.c
  src/ksp/v4ksp_driver.cpp
Labels: Aniket-2023

#325 GSoC 2023: Yige Huang week 8
  docqueries/withPoints/doc-pgr_withPointsDD.result
  docqueries/withPoints/doc-pgr_withPointsDD.test.sql
  include/driving_distance/withPointsDD.hpp
  pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg
  pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg
  src/driving_distance/CMakeLists.txt
  src/driving_distance/many_to_dist_withPointsDD.c
  src/driving_distance/withPointsDD.c
  src/driving_distance/withPointsDD_driver.cpp
  src/driving_distance/withPoints_dd_driver.cpp
Labels: yige-2023

#327 GSoC 2023: Abhinav Jain week 8
  include/drivers/yen/withPoints_ksp_driver.h
  include/yen/pgr_ksp.hpp
  pgtap/ksp/withPointsKSP/inner_query.pg
  pgtap/ksp/withPointsKSP/types_check.pg
  sql/ksp/withPointsKSP.sql
  sql/sigs/pgrouting--3.6.sig
  src/ksp/withPoints_ksp.c
  src/ksp/withPoints_ksp_driver.cpp
Labels: Abhinj-2023

#329 GSoC 2023: Aryan Gupta week 8
  include/cpp_common/pgr_base_graph.hpp
  include/dijkstra/v4drivingDist.hpp
  include/drivers/driving_distance/v4drivedist_driver.h
  pgtap/dijkstra/driving_distance/edge_cases/issue_1152.pg
  pgtap/dijkstra/driving_distance/edge_cases/issue_519.pg
  pgtap/dijkstra/driving_distance/types_check.pg
  sql/driving_distance/_drivingDistance.sql
  sql/driving_distance/drivingDistance.sql
  sql/sigs/pgrouting--3.6.sig
Labels: aryan-2023

#330 GSoC 2023: Aniket Agarwal week 9
  doc/ksp/pgr_KSP.rst
  doc/src/migration.rst
  docqueries/src/migration.result
  docqueries/src/migration.test.sql
  pgtap/ksp/ksp/no_crash_test.pg
Labels: Aniket-2023

#332 GSoC 2023: Yige Huang week 9
  doc/src/migration.rst
  doc/withPoints/pgr_withPointsDD.rst
  docqueries/src/migration.result
  docqueries/src/migration.test.sql
Labels: yige-2023

#331 GSoC 2023: Aryan Gupta week 9
  doc/driving_distance/pgr_drivingDistance.rst
  doc/src/migration.rst
  include/cpp_common/pgr_base_graph.hpp
  include/dijkstra/v4drivingDist.hpp
  pgtap/dijkstra/driving_distance/edge_cases/issue_1152.pg
  pgtap/dijkstra/driving_distance/edge_cases/issue_519.pg
  pgtap/dijkstra/driving_distance/inner_query.pg
  pgtap/dijkstra/driving_distance/no_crash_test.pg
  pgtap/dijkstra/driving_distance/types_check.pg
Labels: aryan-2023

#333 GSoC 2023: Abhinav Jain Week 9
  doc/conf.py.in
  doc/src/migration.rst
  doc/withPoints/pgr_withPointsKSP.rst
  docqueries/src/migration.result
  docqueries/src/migration.test.sql
  docqueries/withPoints/withPointsKSP.result
  docqueries/withPoints/withPointsKSP.test.sql
  src/ksp/withPoints_ksp.c
Labels: Abhinj-2023
