Repository pgRouting/GSoC-pgRouting, pull requests merged in 2025-07, with the labels that each got.

#460 Week 5 sloan ordering
  doc/ordering/ordering-family.rst
  docqueries/ordering/CMakeLists.txt
  docqueries/ordering/sloanOrdering.pg
  docqueries/ordering/sloanOrdering.result
  docqueries/ordering/test.conf
  include/drivers/ordering_driver.hpp
  include/ordering/sloanOrdering.hpp
  include/process/ordering_process.h
  pgtap/ordering/sloan/types_check.pg
  sql/ordering/_sloanOrdering.sql
  sql/ordering/sloanOrdering.sql
  sql/sigs/pgrouting--4.0.sig
  src/ordering/CMakeLists.txt
  src/ordering/ordering_driver.cpp
  src/ordering/ordering_process.cpp
  src/ordering/sloanOrdering.c
Labels: bipashabg-2025

#466 Week 6 sloan ordering
  docqueries/ordering/sloanOrdering.pg
  docqueries/ordering/sloanOrdering.result
  docqueries/ordering/test.conf
  include/ordering/sloanOrdering.hpp
  sql/ordering/sloanOrdering.sql
  src/ordering/ordering_driver.cpp
  src/ordering/sloanOrdering.c
Labels: bipashabg-2025

#464 Week 6 king and minimumdegree ordering
  docqueries/ordering/kingOrdering.result
  docqueries/ordering/minDegreeOrdering.result
  include/drivers/ordering_driver.hpp
  include/ordering/ordering.hpp
  include/process/ordering_process.h
  just_to_start_week6
  src/ordering/CMakeLists.txt
  src/ordering/kingOrdering.c
  src/ordering/minDegreeOrdering.c
  src/ordering/ordering_driver.cpp
  src/ordering/ordering_process.cpp
Labels: wifi-2025

#467 Week 7 king minimum ordering
  docqueries/ordering/kingOrdering.pg
  include/ordering/ordering.hpp
  just_to_start_week6
  src/ordering/ordering_driver.cpp
Labels: wifi-2025

#469 Week 7 sloanordering
  docqueries/ordering/sloanOrdering.pg
  docqueries/ordering/sloanOrdering.result
  include/ordering/sloanOrdering.hpp
  src/ordering/ordering_driver.cpp
  src/ordering/sloanOrdering.c
Labels: bipashabg-2025

#470 Week-7-bandwidth
  include/drivers/metrics_driver.hpp
  include/metrics/bandwidth.hpp
  pgtap/metrics/bandwidth/types_check.pg
  src/metrics/bandwidth.c
  src/metrics/metrics_driver.cpp
  src/metrics/metrics_process.cpp
Labels: saloni-2025

#473 Week-8-bandwidth
  pgtap/metrics/bandwidth/edge_cases.pg
  pgtap/metrics/bandwidth/inner_query.pg
  pgtap/metrics/bandwidth/no_crash_test.pg
  src/metrics/metrics_driver.cpp
  tools/testers/no_crash_test.sql
Labels: saloni-2025
