Repository pgRouting/GSoC-pgRouting, pull requests merged in 2025-08, with the labels that each got.

#474 Week-9-bandwidth
  doc/_static/page_history.js
  doc/metrics/CMakeLists.txt
  doc/metrics/pgr_bandwidth.rst
  docqueries/metrics/bandwidth.pg
  docqueries/metrics/bandwidth.result
Labels: saloni-2025

#476 Week 9 king minimum ordering
  doc/_static/page_history.js
  doc/ordering/CMakeLists.txt
  doc/ordering/ordering-family.rst
  doc/ordering/pgr_cuthillMckeeOrdering.rst
  doc/ordering/pgr_kingOrdering.rst
  doc/ordering/pgr_minDegreeOrdering.rst
  docqueries/ordering/CMakeLists.txt
  include/drivers/ordering/kingOrdering_driver.h
  include/drivers/ordering/minimumDegreeOrdering_driver.h
  just_start_week8
  pgtap/ordering/kingOrdering/edge_cases.pg
  pgtap/ordering/minDegreeOrdering/edge_cases.pg
Labels: wifi-2025

#483 Week 12 bandwidth
  doc/src/pgRouting-introduction.rst
Labels: saloni-2025

#480 Week 11 king minimum ordering
  .gitignore
  docqueries/ordering/kingOrdering.result
  include/ordering/kingOrdering.hpp
  include/ordering/minDegreeOrdering.hpp
  just_start_week11
  src/ordering/ordering_driver.cpp
Labels: wifi-2025

#485 Week 12 sloan ordering
  doc/src/pgRouting-introduction.rst
Labels: bipashabg-2025
